### ISSUE TITLE
Consider adding a `throw` method.

### ISSUE THREAD

**Issue by tobyink** [FGasper/p5-X-Tiny#2]
So instead of:

```
die My::Module::X->create(...);
```

People can just call:

```
My::Module::X->throw(...);
```

With no `die`.

It's not a necessity but most other exception classes seem to provide it, so it may help people switching to X::Tiny from other exception classes.

**Comment by FGasper** [comment]
@tobyink Do code analysis tools like Perl::Critic recognize that syntax?

I’ve never sympathized with the rationale for such methods. It saves only a few keystrokes, and it “fragments” the syntax for perhaps the most crucial flow-control mechanism.

**Comment by tobyink** [comment]
It's just a class method call like `Some::Class->new(...)` or `DBI->connect(...)`. Why wouldn't Perl::Critic recognize it?

**Comment by FGasper** [comment]
What I mean is, does it recognize it as an exception throw?

Consider such code:
```
die Some::Class->new(@args);

return 123;
```
^^ P::C can flag the unreachable code in the above because it recognizes `die()`. Can that be said for a `throw()` method?

**Comment by tobyink** [comment]
It doesn't as far as I'm aware, which is odd because Perl::Critic makes extensive use of `throw` functions internally.
